# Generated by Django 4.1.2 on 2022-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redwingsapp', '0002_alter_donor_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(max_length=3)),
                ('last_time_donated', models.DateField()),
            ],
        ),
    ]
