# Generated by Django 4.1.2 on 2022-10-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blooddonation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="firstname",
            new_name="firstnamee",
        ),
    ]
