# Generated by Django 4.1.2 on 2022-10-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blooddonation", "0002_request_statistic_alter_donor_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name="Statistic",
        ),
    ]
