# Generated by Django 4.1.2 on 2022-10-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blooddonation", "0002_rename_firstname_request_firstnamee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="firstnamee",
            new_name="first_name",
        ),
    ]
