# Generated by Django 4.1.2 on 2022-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blooddonation", "0003_newuser_delete_statistic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="password",
            field=models.CharField(max_length=8),
        ),
    ]
