# Generated by Django 4.1.2 on 2022-10-23 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blooddonation", "0003_rename_firstnamee_request_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
